---

- name: install basic software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - wget 
    - git 
    - net-tools
    - bind-utils 
    - iptables-services 
    - bridge-utils 
    - bash-completion 
    - kexec-tools 
    - psacct
    - vim 
    - ntp
    - NetworkManager
    - centos-release-openshift-origin

- name: start NetworkManager service 
  service: name=NetworkManager enabled=yes state=started
